from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


def utcnow() -> datetime:
    return datetime.now(timezone.utc).replace(tzinfo=None)


@dataclass
class Conversation:
    user_email: str
    title: str
    surface: str = "chat"
    project_id: str | None = None
    id: int | None = None
    created_at: datetime = field(default_factory=utcnow)
    updated_at: datetime = field(default_factory=utcnow)


@dataclass
class MabelProject:
    id: str
    owner_email: str
    name: str
    description: str = ""
    instructions: str = ""
    color: str = "slate"
    created_at: datetime = field(default_factory=utcnow)
    updated_at: datetime = field(default_factory=utcnow)


@dataclass
class AgentRun:
    id: str
    conversation_id: int | None
    user_email: str
    surface: str
    status: str
    model: str
    state_json: dict[str, Any] | None = None
    trace_id: str | None = None
    created_at: datetime = field(default_factory=utcnow)
    finished_at: datetime | None = None


@dataclass
class Message:
    conversation_id: int
    role: str
    content: str
    sources: list[dict[str, Any]] = field(default_factory=list)
    # Links an assistant message back to the AgentRun that produced it. Used
    # by the frontend on conversation reload to attach tool cards + sources
    # to the EXACT turn that owned them (instead of the first assistant
    # message in the thread, which was the prior bug).
    run_id: str | None = None
    id: int | None = None
    created_at: datetime = field(default_factory=utcnow)


@dataclass
class ToolCall:
    run_id: str
    tool_name: str
    status: str
    server_slug: str | None = None
    scope: str = "read"
    arguments: dict[str, Any] = field(default_factory=dict)
    output_preview: str | None = None
    id: int | None = None
    created_at: datetime = field(default_factory=utcnow)


@dataclass
class Approval:
    id: str
    status: str
    title: str
    summary: str
    requested_by: str
    payload: dict[str, Any]
    run_id: str | None = None
    decided_by: str | None = None
    decision_reason: str | None = None
    created_at: datetime = field(default_factory=utcnow)
    updated_at: datetime = field(default_factory=utcnow)


@dataclass
class ConnectorSnapshot:
    org_slug: str
    server_slug: str
    name: str
    connection_status: str
    tools: list[dict[str, Any]] = field(default_factory=list)
    last_error: str | None = None
    enabled: bool | None = True
    id: int | None = None
    refreshed_at: datetime = field(default_factory=utcnow)


@dataclass
class Skill:
    id: str
    name: str
    owner_team: str
    status: str
    current_version: str
    content_md: str
    mcp_bindings: list[dict[str, Any]] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    source: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=utcnow)
    updated_at: datetime = field(default_factory=utcnow)


@dataclass
class StarterPack:
    id: str
    name: str
    owner_team: str
    role_key: str
    status: str
    commands: list[dict[str, Any]] = field(default_factory=list)
    skill_ids: list[str] = field(default_factory=list)
    connector_slugs: list[str] = field(default_factory=list)
    policies: dict[str, Any] = field(default_factory=dict)
    created_at: datetime = field(default_factory=utcnow)
    updated_at: datetime = field(default_factory=utcnow)


@dataclass
class ScheduledTask:
    id: str
    owner_email: str
    name: str
    prompt: str
    schedule_kind: str
    cron: str
    timezone: str = "UTC"
    status: str = "active"
    mode: str = "standalone"
    workflow_id: str | None = None
    notification_mode: str = "inbox"
    last_run_at: datetime | None = None
    next_run_at: datetime | None = None
    created_at: datetime = field(default_factory=utcnow)
    updated_at: datetime = field(default_factory=utcnow)


@dataclass
class ScheduledTaskRun:
    id: str
    task_id: str
    owner_email: str
    status: str
    summary: str
    conversation_id: int | None = None
    workflow_run_id: str | None = None
    created_at: datetime = field(default_factory=utcnow)
    finished_at: datetime | None = None


@dataclass
class AuditEvent:
    actor_email: str
    event_type: str
    status: str
    metadata: dict[str, Any] = field(default_factory=dict)
    id: int | None = None
    created_at: datetime = field(default_factory=utcnow)


@dataclass
class UploadedFile:
    """A file in Mabel's file lake — either uploaded by a user as a chat
    attachment, or generated by the agent (code interpreter / image tool).

    `local_path` is the on-disk path under settings.uploads_dir. `openai_file_id`
    is the id minted by OpenAI's Files API when the file was sent to the model.
    For agent-generated files, `openai_file_id` may also be the container file
    id used to fetch raw bytes from the code interpreter container.
    """

    owner_email: str
    name: str
    mime_type: str
    size_bytes: int
    source: str  # "user_upload" | "agent_image" | "agent_code_file"
    local_path: str
    openai_file_id: str | None = None
    conversation_id: int | None = None
    project_id: str | None = None
    run_id: str | None = None
    id: str = ""
    created_at: datetime = field(default_factory=utcnow)


@dataclass
class ConversationFileLink:
    id: str
    file_id: str
    owner_email: str
    conversation_id: int
    run_id: str
    created_at: datetime = field(default_factory=utcnow)


@dataclass
class MabelDocument:
    id: str
    owner_email: str
    title: str
    kind: str  # markdown | html | csv | text
    content: str
    conversation_id: int | None = None
    created_at: datetime = field(default_factory=utcnow)
    updated_at: datetime = field(default_factory=utcnow)


@dataclass
class MabelMemoryItem:
    id: str
    owner_email: str
    key: str
    content: str
    tags: list[str] = field(default_factory=list)
    embedding: list[float] = field(default_factory=list)
    pinned: bool = False
    confidence: float = 0.7
    source: str = "manual"
    conversation_id: int | None = None
    last_used_at: datetime | None = None
    created_at: datetime = field(default_factory=utcnow)
    updated_at: datetime = field(default_factory=utcnow)


@dataclass
class PromptInboxItem:
    id: str
    run_id: str
    conversation_id: int | None
    owner_email: str
    mode: str  # "steer" | "queue"
    prompt: str
    status: str = "pending"  # pending | applied | cancelled
    created_at: datetime = field(default_factory=utcnow)
    updated_at: datetime = field(default_factory=utcnow)
